pullRequestOpened: >
  Thank you for opening this pull request, your code will be reviewed soon! 
  
  Important Notes:
  
  
  We are limiting contributions per person to 4 additions across EmojiScreen, EmojiBops and EmojiPages. Please limit yourself to up to 4 additions across the three emoji projects. (Example One: Complete 1 feature, add two movies, and add one song; Example Two: complete 4 Issues for movies; Example Three: add one song, 2 movies and one book, etc). This is due to the high level of activity on these projects at the moment. Some Issues ask you to add multiple movies, those Issues count as 1 addition. We want to make sure many people have a chance to contribute. The limit will be lifted once the activity has died down. 🙂
  
  
  If any updates need to be made, I will leave a comment for you here outlining exactly what you need to change for your pull request to be accepted. 💖
  
  
  In the meantime, feel free to contribute to one of my other projects: 
  
  📚 EmojiPages - A listing of books and plays. (https://github.com/brittanyrw/emojipages)
  
  🎶 EmojiBops - A listing of songs. (https://github.com/brittanyrw/emojibops)
