pullRequestOpened: >
  Thank you for opening this pull request, your code will be reviewed soon! 
  
  Important Notes:
  
  
  There is a limit to the number of pull requests you can make on this project due to the large amount of activity. Please limit yourself to up to 4 additions to this project. (Example: Complete 1 feature and add three movies, complete 4 Issues for movies and add one feature, add four movies, etc). Some Issues ask that you add mulitple shows/movies, that will count as 1 addition. The limit will be removed in the future but for now I want to allow as many people as possible to have the chance contribute. 
  
  
  If any updates need to be made, I will leave a comment for you here outlining exactly what you need to change for your pull request to be accepted. 💖
  
  
  In the meantime, feel free to contribute to one of my other projects: 
  
  📚 EmojiPages - A listing of books and plays. (https://github.com/brittanyrw/emojipages)
  
  🎶 EmojiBops - A listing of songs. (https://github.com/brittanyrw/emojibops)
